---
title: "Reading chl-a and SST data"
output: html_notebook
---


```{r}
# install.packages("ncdf4")  ## install ncdf4 package to read netcdf files
# install.packages("raster") ## raster is used to process lat lon data
library(ncdf4)
library(raster)
```

reading chl-a data
```{r}
# download chl data - northwest - small
data = nc_open("nw_chl_small.nc") ## load the netcdf file into R
# print(data) ## display the data 

# temp <- ncvar_get(data,"sst") ## Create a temp matrix using sst in the netcdf file
chl <- ncvar_get(data,"chlor_a") ## Create a matrix of chlorophyll a data
lat <- ncvar_get(data,"latitude") ## create a vector of latitudes
lon <- ncvar_get(data,"longitude") ## create a vector of longitudes
time <- ncvar_get(data,"time") ##create a time vector

dim(time) ## display dimensions of the time vector 
dim(lat) ## display dimensions of the lat vector 
dim(lon) ## display dimensions of the lon vector 
dim(chl) ## display dimensions of the chl matrix 
# dim(temp) ## display dimensions of the temp matrix

ncatt_get(data,"time","units") ## time in "seconds since 1970-1-1 00:00:00"
ncatt_get(data,"chlor_a","units") ## chla in mg/m3
nc_close(data)

time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) ## convert to YYYY-M-D time format

# which(time=="2005-01-01") ## to find the position for a certain date

chl_a <-apply(chl, c(3), mean,na.rm=TRUE)
summary(chl_a)

chl_nw_s<-data.frame(time,chl_a)
```

```{r}
# download chl data - northwest - large
data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_chl_large.nc") ## load the netcdf file into R

chl <- ncvar_get(data,"chlor_a") ## Create a matrix of chlorophyll a data
lat <- ncvar_get(data,"latitude") ## create a vector of latitudes
lon <- ncvar_get(data,"longitude") ## create a vector of longitudes
time <- ncvar_get(data,"time") ##create a time vector
nc_close(data)

time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) ## convert to YYYY-M-D time format

chl_a <-apply(chl, c(3), mean,na.rm=TRUE)
summary(chl_a)

chl_nw_l<-data.frame(time,chl_a)
```

```{r}
# download chl data - southeast - small
data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_chl_small_1.nc") ## load the netcdf file into R

chl <- ncvar_get(data,"chlor_a") ## Create a matrix of chlorophyll a data
time <- ncvar_get(data,"time") ##create a time vector
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) ## convert to YYYY-M-D time format

chl_a <-apply(chl, c(3), mean,na.rm=TRUE)
chl_se_s_1<-data.frame(time,chl_a)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_chl_small_2.nc") ## load the netcdf file into R

chl <- ncvar_get(data,"chlor_a") ## Create a matrix of chlorophyll a data
time <- ncvar_get(data,"time") ##create a time vector
nc_close(data)

time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) ## convert to YYYY-M-D time format

chl_a <-apply(chl, c(3), mean,na.rm=TRUE)

chl_se_s_2<-data.frame(time,chl_a)

chl_se_s<-rbind(chl_se_s_1,chl_se_s_2)
remove(chl_se_s_1,chl_se_s_2)
```

```{r}
# download chl data - southeast - large
data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_chl_large_1.nc") ## load the netcdf file into R

chl <- ncvar_get(data,"chlor_a") ## Create a matrix of chlorophyll a data
lat <- ncvar_get(data,"latitude") ## create a vector of latitudes
lon <- ncvar_get(data,"longitude") ## create a vector of longitudes
time <- ncvar_get(data,"time") ##create a time vector
nc_close(data)

time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) ## convert to YYYY-M-D time format

chl_a <-apply(chl, c(3), mean,na.rm=TRUE)
summary(chl_a)

chl_se_l_1<-data.frame(time,chl_a)

# download chl data - southeast - large
data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_chl_large_2.nc") ## load the netcdf file into R

chl <- ncvar_get(data,"chlor_a") ## Create a matrix of chlorophyll a data
lat <- ncvar_get(data,"latitude") ## create a vector of latitudes
lon <- ncvar_get(data,"longitude") ## create a vector of longitudes
time <- ncvar_get(data,"time") ##create a time vector
nc_close(data)

time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) ## convert to YYYY-M-D time format

chl_a <-apply(chl, c(3), mean,na.rm=TRUE)
summary(chl_a)

chl_se_l_2<-data.frame(time,chl_a)

chl_se_l<-rbind(chl_se_l_1,chl_se_l_2)
remove(chl_se_l_1,chl_se_l_2)

```


#combine my chl-a dataset
```{r}
chl_nw<-merge(chl_nw_l,chl_nw_s,by="time")
colnames(chl_nw)<-c("date","large","small")
remove(chl_nw_l,chl_nw_s)

chl_se<-merge(chl_se_l,chl_se_s,by="time")
colnames(chl_se)<-c("date","large","small")
remove(chl_se_l,chl_se_s)
```

reading SST data

nw_night
```{r}
data["var"]
# download chl data - northwest - small
data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_sst_1.nc") ## load the netcdf file into R
sst <- ncvar_get(data,"sea_surface_temperature") ## Create a temp matrix using sst in the netcdf file
time <- ncvar_get(data,"time") ##create a time vector
nc_close(data)

time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) ## convert to YYYY-M-D time format
sst <-apply(sst, c(3), mean,na.rm=TRUE)

sst_nw_1<-data.frame(time,sst)


data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_sst_2.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_nw_2<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_sst_3.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_nw_3<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_sst_4.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_nw_4<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_sst_5.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_nw_5<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_sst_6.nc")
sst <- ncvar_get(data,"analysed_sst") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_nw_6<-data.frame(time,sst)


sst_nw<-rbind(sst_nw_1,sst_nw_2,sst_nw_3,sst_nw_4,sst_nw_5,sst_nw_6)
remove(sst_nw_1,sst_nw_2,sst_nw_3,sst_nw_4,sst_nw_5,sst_nw_6)
```


sst- nw - large
```{r}
data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_sst_l_1.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_1<-data.frame(time,sst)


data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_sst_l_2.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_2<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/nw_sst_l_3.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_3<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_4.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_4<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_5.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_5<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_6.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_6<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_7.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_7<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_8.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_8<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_9.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_9<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_10.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_10<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_11.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_11<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_12.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_12<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_13.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_13<-data.frame(time,sst)

```



se_night
```{r}
data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_1.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_1<-data.frame(time,sst)


data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_2.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_2<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_3.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_3<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_4.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_4<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_5.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_5<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_6.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_6<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_7.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_7<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_8.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_8<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_9.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_9<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_10.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_10<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_11.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_11<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_12.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_12<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_13.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_13<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_14.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_14<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_15.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_15<-data.frame(time,sst)

data = nc_open("/Users/lyra/Documents/GitHub/DGwhale/My data/environmental data/se_sst_16.nc")
sst <- ncvar_get(data,"sea_surface_temperature") 
time <- ncvar_get(data,"time") 
nc_close(data)
time <- as.Date(as.POSIXct(time,origin="1970-01-01T00:00:00Z")) 
sst <-apply(sst, c(3), mean,na.rm=TRUE)
sst_se_16<-data.frame(time,sst)

sst_se<-rbind(sst_se_1,sst_se_2,sst_se_3,sst_se_4,sst_se_5,sst_se_6,sst_se_7,sst_se_8,sst_se_9,sst_se_10,sst_se_11,sst_se_12,sst_se_13,sst_se_14,sst_se_15,sst_se_16)
remove(sst_se_1,sst_se_2,sst_se_3,sst_se_4,sst_se_5,sst_se_6,sst_se_7,sst_se_8,sst_se_9,sst_se_10,sst_se_11,sst_se_12,sst_se_13,sst_se_14,sst_se_15,sst_se_16)

```


summary
```{r}
chl_nw$year<-as.numeric(substr(chl_nw$date, 1, 4))
chl_nw$month<-as.numeric(substr(chl_nw$date, 6, 7))
mean_chl_nw_small<-chl_nw %>% group_by(year) %>% summarise(mean=mean(small,na.rm=TRUE))
mean_chl_nw_large<-chl_nw %>% group_by(year) %>% summarise(mean=mean(large,na.rm=TRUE))

chl_se$year<-as.numeric(substr(chl_se$date, 1, 4))
chl_se$month<-as.numeric(substr(chl_se$date, 6, 7))
mean_chl_se_small<-chl_se %>% group_by(year) %>% summarise(mean=mean(small,na.rm=TRUE))
mean_chl_se_clarge<-chl_se %>% group_by(year) %>% summarise(mean=mean(large,na.rm=TRUE))


chl_nw_winter<-subset(chl_nw,month>5 & month<12)
mean_chl_nw_small_winter<-chl_nw_winter %>% group_by(year) %>% summarise(mean=mean(small,na.rm=TRUE))
mean_chl_nw_large_winter<-chl_nw_winter %>% group_by(year) %>% summarise(mean=mean(large,na.rm=TRUE))

chl_se_winter<-subset(chl_se,month>5 & month<12)
mean_chl_se_small_winter<-chl_se_winter %>% group_by(year) %>% summarise(mean=mean(small,na.rm=TRUE))
mean_chl_se_large_winter<-chl_se_winter %>% group_by(year) %>% summarise(mean=mean(large,na.rm=TRUE))

chl_nw_summer<-subset(chl_nw,month< 6| month==12)
mean_chl_nw_small_summer<-chl_nw_summer %>% group_by(year) %>% summarise(mean=mean(small,na.rm=TRUE))
mean_chl_nw_large_summer<-chl_nw_summer %>% group_by(year) %>% summarise(mean=mean(large,na.rm=TRUE))

chl_se_summer<-subset(chl_se,month< 6| month==12)
mean_chl_se_small_summer<-chl_se_summer %>% group_by(year) %>% summarise(mean=mean(small,na.rm=TRUE))
mean_chl_se_large_summer<-chl_se_summer %>% group_by(year) %>% summarise(mean=mean(large,na.rm=TRUE))

```


boxplot for chl-a nw &se small,large allyear

```{r}
mean_chl_nw_small$location<-rep(c("nw"))
mean_chl_nw_small$time<-rep(c("all_year"))

mean_chl_nw_small_summer$location<-rep(c("nw"))
mean_chl_nw_small_summer$time<-rep(c("summer"))

mean_chl_nw_small_winter$location<-rep(c("nw"))
mean_chl_nw_small_winter$time<-rep(c("winter"))

mean_chl_nw<-rbind(mean_chl_nw_small,mean_chl_nw_small_summer,mean_chl_nw_small_winter)


mean_chl_se_small$location<-rep(c("se"))
mean_chl_se_small$time<-rep(c("all_year"))

mean_chl_se_small_summer$location<-rep(c("se"))
mean_chl_se_small_summer$time<-rep(c("summer"))

mean_chl_se_small_winter$location<-rep(c("se"))
mean_chl_se_small_winter$time<-rep(c("winter"))
mean_chl_se<-rbind(mean_chl_se_small,mean_chl_se_small_summer,mean_chl_se_small_winter)

mean_chl<-rbind(mean_chl_nw,mean_chl_se)

```

```{r}
ggplot(mean_chl, aes(x=time, y=mean, fill=location)) + 
  geom_boxplot()+
  labs(title="Food availability by locations",y="chlorophyll-a concentration(mg/m^3)")
```

